name: Publish to PyPI
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build distributions
        run: python -m build --sdist --wheel

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@v1
        with:
          token-source: oidc
          skip-existing: true